method: bayes
metric:
  goal: minimize
  name: valid_rmse
parameters:
  bs:
    distribution: q_uniform
    max: 4096
    min: 512
    q: 512
  dataset:
    value: dblp
  device:
    value: cuda:0
  dropout:
    values:
    - 0.005
    - 0.001
    - 0.05
    - 0.01
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
  epochs:
    value: 1000
  layer_dims:
    values:
    - 3,4,4,1
    - 3,4,8,1
    - 3,8,4,1
    - 3,8,8,1
    - 3,4,8,4,1
    - 3,4,8,16,8,4,1
    - 3,16,32,1
    - 3,16,32,16,1
    - 3,8,16,32,16,8,1
  lr:
    values:
    - 0.001
    - 0.0001
  neg_sampling:
    value: neg_sample0
  nn:
    value: mlp
  rank:
    distribution: int_uniform
    max: 4
    min: 1
  rpath:
    value: /home/dahn017/intern/cisco23
  wd:
    values:
    - 0.001
    - 0.0005
    - 0.0001
    - 5.0e-05
    - 1.0e-05
program: src/main.py
