method: bayes
metric:
  goal: minimize
  name: valid_rmse
parameters:
  bs:
    distribution: int_uniform
    max: 2048
    min: 512
  dataset:
    value: SG
  device:
    value: cuda:0
  dropout:
    distribution: uniform
    max: 1
    min: 0
  epochs:
    value: 1000
  layer_dims:
    values:
    - 3,4,4,1
    - 3,4,8,1
    - 3,8,4,1
    - 3,8,8,1
    - 3,4,8,4,1
    - 3,4,8,16,8,4,1
    - 3,16,32,1
    - 3,16,32,16,1
    - 3,8,16,32,16,8,1
  lr:
    distribution: uniform
    max: 0.001
    min: 0.0001
  neg_sampling:
    value: neg_sample0
  nn:
    value: mlp
  rank:
    distribution: int_uniform
    max: 16
    min: 1
  rpath:
    value: /home/dahn017/intern/cisco23
  wd:
    distribution: uniform
    max: 0.001
    min: 1.0e-06
program: src/main.py
