method: grid
metric:
  goal: minimize
  name: valid_rmse
parameters:
  act:
    values:
    - rational
    - relu
    - exu
  bs:
    values:
    - 1024
    - 2048
    - 4096
  dataset:
    value: yelp
  device:
    value: cuda:0
  dropout:
    values:
    - 0.0001
    - 0.005
    - 0.001
  epochs:
    value: 10000
  layer_dims:
    values:
    - 3, 1
    - 3, 4, 1
    - 3, 8, 1
    - 3, 16, 1
    - 3, 32, 1
    - 3,4,8,1
    - 3,4,8,4,1
    - 3,4,8,16,8,4,1
    - 3,16,32,1
    - 3,8,16,32,16,8,1
  lr:
    values:
    - 0.001
    - 0.0001
  nn:
    value: mlp
  rank:
    values:
    - 1
    - 2
    - 3
    - 8
    - 16
    - 32
  rpath:
    value: /home/dahn017/intern/cisco23/neat
  wd:
    values:
    - 0.001
    - 0.0005
    - 0.0001
    - 5.0e-05
    - 1.0e-05
program: src/main.py
