method: bayes
metric:
  goal: minimize
  name: valid_rmse
parameters:
  bs:
    q: 512
    min: 512
    max: 4096
  distribution: q_uniform
  dataset:
    value: yelp
  device:
    value: cuda:0
  dropout:
    q: 0.01
    max: 1
    min: 0
    distribution: q_log_uniform
  epochs:
    value: 1000
  layer_dims:
    values:
    - 3,4,4,1
    - 3,4,8,1
    - 3,8,4,1
    - 3,8,8,1
    - 3,4,8,4,1
    - 3,4,8,16,8,4,1
    - 3,16,32,1
    - 3,16,32,16,1
    - 3,8,16,32,16,8,1
  lr:
    values:
      - 0.001
      - 0.0001
  neg_sampling:
    value: neg_sample0
  nn:
    value: mlp
  rank:
    distribution: int_uniform
    max: 4
    min: 1
  rpath:
    value: /home/dahn017/intern/cisco23
  wd:
    values:
    - 0.001
    - 0.0005
    - 0.0001
    - 0.00005
    - 0.00001
program: src/main.py
