method: bayes
metric:
  goal: minimize
  name: valid_rmse
parameters:
  act:
    value: relu
  bs:
    values:
    - 1024
  dataset:
    value: yahoo_msg
  device:
    value: cuda:2
  dropout:
    distribution: q_uniform
    max: 1
    min: 0
    q: 0.1
  dropout2:
    distribution: q_uniform
    max: 1
    min: 0
    q: 0.1
  epochs:
    value: 10000
  layer_dims:
    values:
    - 3,8,1
    - 3,16,1
    - 3,32,1
    - 3,64,1
    - 3, 16, 32, 1
  lr:
    values:
    - 0.001
  nn:
    value: mlp
  rank:
    values:
    - 8
    - 16
    - 32
    - 64
    - 128
  rpath:
    value: /data/dahn017/NeAT/bceloss
  wd:
    values:
    - 0.0001
    - 0.00001
  lossf:
    value: BCELoss
program: src/main.py
