method: grid
metric:
  goal: minimize
  name: valid_rmse
parameters:
  dataset:
    value: ml
  rpath:
    value: /home/dahn017/intern/cisco23/neat
  device:
    value: cuda:0
  nn:
    value: none
  tf:
    value: "cp+act"
  epochs:
    value: 10000
  bs:
    value: 2048
  rank:
    values:
    - 8
    - 16
    - 32
  act:
    values:
    - relu
    - leakyrelu
    - elu
    - gelu
    - selu
    - prelu
    - rational
  lr:
    values:
    - 0.001
  wd:
    values:
    - 0.0001
    - 1.0e-05
program: src/main.py
