method: grid
metric:
  goal: minimize
  name: valid_rmse
parameters:
  dataset:
    value: yelp
  rpath:
    value: /home/dahn017/intern/cisco23/neat
  device:
    value: cuda:1
  nn:
    value: mlp
  epochs:
    value: 10000
  dropout:
    value: 0.0001
  bs:
    value: 2048
  layer_dims:
    values:
      - 3, 1
      - 3, 4, 1
      - 3, 8, 1
  rank:
    values:
    - 8
    - 16
    - 32
  act:
    values:
    - relu
    - leakyrelu
    - elu
    - gelu
    - selu
    - rational
  lr:
    values:
    - 0.001
  wd:
    values:
    - 0.0001
    - 1.0e-05
program: src/main.py
