method: bayes
metric:
  goal: minimize
  name: valid_rmse
parameters:
  act:
    value: relu
  bs:
    values:
    - 2048
  dataset:
    value: foursquare_tky
  device:
    value: cuda:2
  dropout:
    distribution: q_uniform
    max: 1
    min: 0
    q: 0.1
  epochs:
    value: 10000
  layer_dims:
    values:
    - 3,4,1
    - 3,8,1
    - 3,16,1
    - 3,32,1
    - 3,64,1
  lr:
    values:
    - 0.001
  nn:
    value: mlp
  rank:
    values:
    - 8
    - 16
    - 32
    - 64
  rpath:
    value: /data/dahn017/NeAT/dropout
  wd:
    values:
    - 0.001
    - 0.0001
program: src/main.py
